config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/', redirect: '/dashboard'
  # get '/dashboard', to: 'dashboard#index'
  get '/dashboard', to: 'dashboard#index'
  get '/', to: redirect('dashboard')
  resources :sessions, only: %i[new create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  resources :password_resets, only: %i[new create edit update]
  post 'guest_sessions', to: 'sessions#guest_login'

  resources :user_picks
  resources :user_seasons
  resources :users, param: :username do
    resources :user_picks, only: [:index], controller: 'users/user_picks'
  end
  resources :seasons
  resources :leaderboard, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/season.rb
# frozen_string_literal: true

class Season < ApplicationRecord
  validates_uniqueness_of :season_year
  validates :season_year, presence: true

  has_many :user_seasons, dependent: :destroy
  has_many :users, through: :user_seasons

  # def next_race_weekend
  #   schedule = F1Facade.new.get_schedule(season_year)
  #   race_array = schedule[:MRData][:RaceTable][:Races]
  #   race_array.select { |race| Date.parse(race[:date]) >= Date.today }.first
  # end

  def next_race_weekend(season)
    mt_timezone = 'Mountain Time (US & Canada)'
    mt_time_now = Time.now.in_time_zone(mt_timezone).to_date

    schedule = F1Facade.new.get_schedule(season_year)
    race_array = schedule[:MRData][:RaceTable][:Races]
    if season.to_i < mt_time_now.year
      'This season is over. Please select a different season.'
    else
      race_array.select { |race| Date.parse(race[:date]) >= mt_time_now }.first
    end
  end

  def last_race_weekend
    result = F1Facade.new.get_latest_race
    result[:MRData][:RaceTable][:Races][0]
  end
end

app/controllers/seasons_controller.rb
# frozen_string_literal: true

class SeasonsController < ApplicationController
  before_action :set_season, only: %i[show edit update destroy]

  # GET /seasons or /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1 or /seasons/1.json
  def show # rubocop:disable Metrics/AbcSize
    @driver_standings = F1Facade.new.get_driver_standings(@season.season_year)
    @constructor_standings = F1Facade.new.get_constructor_standings(@season.season_year)
    @users = User.all
    @user = User.find_by(username: params[:username])
    @next_race = @season.next_race_weekend(@season.season_year)
    @last_race = @season.last_race_weekend
    @drivers_position = 1
    @constructors_position = 1

    # If a user is selected from the dropdown, redirect to their show page
    return unless params[:username]

    redirect_to user_path(params[:username], season_id: @season.id)
  end

  # GET /seasons/new
  def new
    @hide_header = true
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit; end

  # POST /seasons or /seasons.json

  def create # rubocop:disable Metrics/MethodLength,Metrics/AbcSize
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.season_year.present?
        @season.save
        User.all.each do |user|
          UserSeason.create!(user_id: user.id, season_id: @season.id)
        end
        format.html { redirect_to season_url(@season), notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new, status: :unprocessable_entity, notice: 'Season year cannot be empty.' }
        format.json { render json: { error: 'Season year cannot be empty.' }, status: :unprocessable_entity }
      end
    end
  end

  ## How we had it before
  # def create
  #   @season = Season.new(season_params)

  #   respond_to do |format|
  #     unless @season.season_year.empty?
  #       if @season.save
  #         User.all.each do |user|
  #           UserSeason.create!(user_id: user.id, season_id: @season.id)
  #         end
  #         format.html { redirect_to season_url(@season), notice: 'Season was successfully created.' }
  #         format.json { render :show, status: :created, location: @season }
  #       else
  #         format.html { render :new, status: :unprocessable_entity }
  #         format.json { render json: @season.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  # end

  ## First fix for failing test on line 38 of seasons_controller_spec
  # def create
  #   @season = Season.new(season_params)

  #   respond_to do |format|
  #     if @season.season_year.present?
  #       if @season.save
  #         User.all.each do |user|
  #           UserSeason.create!(user_id: user.id, season_id: @season.id)
  #         end
  #         format.html { redirect_to season_url(@season), notice: 'Season was successfully created.' }
  #         format.json { render :show, status: :created, location: @season }
  #       else
  #         format.html { render :new, status: :unprocessable_entity }
  #         format.json { render json: @season.errors, status: :unprocessable_entity }
  #       end
  #     else
  #       format.html { render :new, status: :unprocessable_entity, notice: 'Season year cannot be empty.' }
  #       format.json { render json: { error: 'Season year cannot be empty.' }, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to season_url(@season), notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_season
    @season = Season.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def season_params
    params.require(:season).permit(:season_year, :id, :user_id)
  end
end

app/helpers/seasons_helper.rb
# frozen_string_literal: true

module SeasonsHelper
  def formatted_date(date_string)
    Date.parse(date_string).strftime('%B %d')
  end

  def formatted_time(time_string)
    time = time_string.to_time.in_time_zone('Mountain Time (US & Canada)')
    time.strftime('%I:%M %p')
  end
end

app/views/seasons/_constructor_standings_table.html.erb
<div id="constructor_table"class="constructor-table-wrapper">
  <h2 class="pt-3 pb-3 text-xl font-bold">Constructor Standings:</h2>
  <% if @constructor_standings == 'Constructor Standings are not availble yet' %>
    <h2><%= @constructor_standings %></h2>
  <% else %>
    <div class="constructor-table"> <!-- This starts the constructors standings table -->
      <table class="">
      <thead class="">
        <tr class="">
          <th class="py-2 center-header">Position</th>
          <th class="py-2 center-header">Constructor</th>
          <th class="py-2 center-header">Wins</th>
          <th class="py-2 center-header">Points</th>
        </tr>
      </thead>
      <tbody>
        <% @constructor_standings.each do |constructor| %>
          <tr class="font-med <%= @constructors_position.even? ? 'bg-red-200 dark:bg-gray-600' : '' %>">
            <th class="py-2 center-text"><%= constructor.position %></td>
            <td class="py-2 center-text"><%= constructor.constructor_name %></td>
            <td class="py-2 center-text"><%= constructor.wins %></td>
            <td class="py-2 center-text"><%= constructor.points %></td>
            <% @constructors_position += 1 %>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div> 
  <% end %>
</div><!-- This ends the constructor standings -->

app/views/seasons/_driver_standings_table.html.erb
<div id="driver_table" class="driver-table-wrapper">
  <h2 class="pt-3 pb-3 text-xl font-bold">Driver Standings:</h2>
  <% if @driver_standings == 'Driver Standings are not yet available' %>
    <h2><%= @driver_standings %></h2>
  <% else %>
    <div class="driver-table"> <!-- This starts the driver's standings table -->
      <table>
        <thead>
        <tr>
          <th class="py-2 center-header">Position</th>
          <th class="py-2 center-header">Points</th>
          <th class="py-2 center-header">Driver Name</th>
          <th class="py-2 center-header">Constructor</th>
        </tr>
        </thead>
        <tbody>
        <% @driver_standings.each do |driver| %>
          <tr>
            <th class="py-2 center-text"><%= driver.position %></td>
            <td class="py-2 center-text"><%= driver.points %></td>
            <td class="py-2 center-text"><%= driver.driver_name %></td>
            <td class="py-2 center-text"><%= driver.constructor %></td>
            <% @drivers_position += 1 %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div> 
  <% end %>   <!-- This ends the driver's standings table -->
</div>

app/views/seasons/_main_show_content.html.erb
<main>
  <div class="page-wrapper">
    <%= render partial: 'title_text' %>
    <%= render partial: 'user_dropdown' %>

    <div class="seasons-page"> 
      <%= render partial: 'standings' %>
      <%= render partial: 'schedule' %>
    </div>
  </div>
<main>

app/views/seasons/_next_race.html.erb
<div id="next_race" class="box">
  <% if @next_race != 'This season is over. Please select a different season.' %>
    <h2 class="font-bold">Next Race: <%= @next_race[:raceName] %></h2>
    <br>
    <h3>Circuit: <%= @next_race[:Circuit][:circuitName]%> </h3>
    <br>
    <h3>Dates:</h3>
    <% if !@next_race[:time] %>
      <h4>Race: <%= formatted_date(@next_race[:date]) %></h4>
    <% else %>
      <h4>Race: <%= formatted_date(@next_race[:date]) %>: <%= formatted_time(@next_race[:time]) %> </h4>
    <% end %>
    <br>
    <% if !@next_race[:time] %>
      <h2> No times for sessions have been scheduled yet </h2>
    <% else %>
      <% if @next_race[:ThirdPractice] %>
        <p>Free Practice 1: <%= formatted_date(@next_race[:FirstPractice][:date]) %>:  <%= formatted_time(@next_race[:FirstPractice][:time]) %></p>
        <p>Free Practice 2: <%= formatted_date(@next_race[:SecondPractice][:date]) %>: <%= formatted_time(@next_race[:SecondPractice][:time]) %></p>
        <p>Free Practice 3: <%= formatted_date(@next_race[:ThirdPractice][:date]) %>: <%= formatted_time(@next_race[:ThirdPractice][:time]) %></p>
        <p>Qualifying: <%= formatted_date(@next_race[:Qualifying][:date]) %>: <%= formatted_time(@next_race[:Qualifying][:time]) %></p>
      <% else %>
        <p>Free Practice 1: <%= formatted_date(@next_race[:FirstPractice][:date]) %>: <%= formatted_time(@next_race[:FirstPractice][:time]) %></p>
        <p>Race Qualifying: <%= formatted_date(@next_race[:Qualifying][:date]) %>: <%= formatted_time(@next_race[:Qualifying][:time]) %></p>
        <p>Sprint Shootout: <%= formatted_date(@next_race[:SecondPractice][:date]) %>: <%= formatted_time(@next_race[:SecondPractice][:time]) %></p>
        <p>Sprint: <%= formatted_date(@next_race[:Sprint][:date]) %>: <%= formatted_time(@next_race[:Sprint][:time]) %></p>
      <% end %>
    <% end %>
  <% else  %>
    <h2>No Next Race Weekend: This season has been completed</h2>
  <% end %>
</div>

app/views/seasons/_schedule.html.erb
<% if @next_race == 'This season is over. Please select a different season.' %>
  <div class="schedule-over-wrapper">
    <br>
    <%= render partial: 'next_race' %>
    <br><br>
    <%= render partial: 'previous_race' %>
  </div>
<% else %>
  <div class="schedule-wrapper">
    <br>
    <%= render partial: 'next_race' %>
    <br><br>
    <%= render partial: 'previous_race' %>
  </div>
<% end %>

app/views/seasons/_season_buttons.html.erb
<div class="div-4 flex">
  <div class="flex-shrink-0 mr-4">
    <div class="font-bold text-blue-700 hover:underline hover:text-red-700">
      <%= link_to 'Edit', edit_season_path(@season) %>
    </div>
  </div>
  <div>
    <div class="font-bold text-blue-700 hover:underline hover:text-red-700">
      <%= link_to 'Back', seasons_path %>
    </div>
  </div>
</div>

app/views/seasons/_standings.html.erb
<div class="seasons-wrapper">
  <!-- <%= render partial: 'season_buttons'%> -->
  <%= render partial: 'driver_standings_table' %>
  <br><br>
  <%= render partial: 'constructor_standings_table' %>
</div>

app/views/seasons/_stylesheet.html.erb
<%= stylesheet_link_tag 'seasons', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/seasons/_title_text.html.erb
<div class="text-wrapper">
  <h2 id="page_title" class="seasons-title">Season at a Glance</h2>
  <p id="season_year" class="season-year">
    Season Year:
    <%= @season.season_year %>
  </p>
</div>

app/views/seasons/_user_dropdown.html.erb
<div id="all_users" class="user-wrapper"> <!-- This starts the user column -->
  <%= form_tag(season_path(@season), method: :get) do %>
    <% users_without_guest = @users.reject { |user| user.username == 'guest' } %>
    <%= select_tag 'username', options_from_collection_for_select(users_without_guest, 'username', 'name', @user.try(:username)), prompt: "Select a user" %>
    <%= submit_tag 'Go', class: 'go-button' %>
  <% end %>

  <% if @season.season_year.to_i == Time.now.year %>
    <%= link_to 'New User', new_user_path(season_id: @season.id), params: {season_id: @season.id}, class: "new-user-button" %>
  <% end %>
</div> <!-- This ends the user-wrapper -->

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<%= stylesheet_link_tag 'seasons_index', media: 'all', 'data-turbolinks-track': 'reload' %>

<p id="notice"><%= notice %></p>
<main>
  <div class="page-wrapper">
    <div class-"form-wrapper">
      <div class="seasons-page">
        <h1 class="title">Seasons</h1>
        <div class="season-table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Season</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @seasons.each do |season| %>
                <tr>
                  <td><%= season.season_year %></td>
                  <td><%= link_to 'Show', season %></td>
                  <td><%= link_to 'Edit', edit_season_path(season) %></td>
                  <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'New Season', new_season_path, class: "button" %>
      </div>
    </div>
  </div>
<main>

app/views/seasons/new.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>
  <%= stylesheet_link_tag 'new_season', media: 'all', 'data-turbolinks-track': 'reload' %>

  <main>
    <div class="page-wrapper"> 
      <div class="form-wrapper">
        <h1 class="title">New Season</h1> 
          <div class="box">
            <%= render 'form', season: @season %>
          </div>
        <%= link_to 'Back', '/', class: "back-button" %>
      </div>
    </div>
  </main>
<% end %>

app/views/seasons/show.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>
  <p id="notice"><%= notice %></p>
  <%= render partial: 'stylesheet' %>
  <%= render partial: 'styles' %>
  <%= render partial: 'main_show_content' %>
<% end %>