config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/', redirect: '/dashboard'
  # get '/dashboard', to: 'dashboard#index'
  get '/dashboard', to: 'dashboard#index'
  get '/', to: redirect('dashboard')
  resources :sessions, only: %i[new create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  resources :password_resets, only: %i[new create edit update]
  post 'guest_sessions', to: 'sessions#guest_login'

  resources :user_picks
  resources :user_seasons
  resources :users, param: :username do
    resources :user_picks, only: [:index], controller: 'users/user_picks'
  end
  resources :seasons
  resources :leaderboard, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_pick.rb
# frozen_string_literal: true

class UserPick < ApplicationRecord
  belongs_to :user
  has_many :user_seasons, through: :user
  has_many :seasons, through: :user_seasons

  validates_presence_of :user_id, :circuit_id

  validate :driver_ids

  validates :circuit_id,
            uniqueness: { scope: %i[user_id season_id], message: 'You can only make one user pick per weekend' }

  def driver_ids
    return unless driver_id_tenth == driver_id_dnf

    errors.add(:driver_id_tenth, "can't be the same as DNF driver")
  end

  def set_current_race
    next_race = F1Facade.new.get_schedule(user.seasons.max.season_year)
    race_array = next_race[:MRData][:RaceTable][:Races]
    current_race = race_array.select { |race| Date.parse(race[:date]) >= Date.today }.first
    current_race[:Circuit][:circuitId]
  end

  def assign_finish_position
    finish = F1Facade.new.get_latest_race

    return unless circuit_id == finish[:MRData][:RaceTable][:Races][0][:Circuit][:circuitId]

    finish[:MRData][:RaceTable][:Races][0][:Results].each do |result|
      if driver_id_dnf == result[:Driver][:driverId] && result[:positionText] == 'R' && result[:position] == '20'
        update(dnf_finish_position: result[:positionText])
      end
      update(tenth_finish_position: result[:position]) if driver_id_tenth == result[:Driver][:driverId]
    end
  end

  def calculate_points
    position = tenth_finish_position
    point_value = Constants::POINT_VALUES[position]
    update(points_earned: self.points_earned += point_value) if point_value
  end

  def dnf_points
    return unless dnf_finish_position == 'R'

    update(points_earned: self.points_earned += 10)
  end

  def self.purify_pick_names
    driver_names = {
      'albon' => 'Alex Albon',
      'alonso' => 'Fernando Alonso',
      'bottas' => 'Valtteri Bottas',
      'de_vries' => 'Nyck de Vries',
      'gasly' => 'Pierre Gasly',
      'hamilton' => 'Lewis Hamilton',
      'hulkenberg' => 'Nico Hülkenberg',
      'leclerc' => 'Charles Leclerc',
      'kevin_magnussen' => 'Kevin Magnussen',
      'norris' => 'Lando Norris',
      'ocon' => 'Esteban Ocon',
      'perez' => 'Sergio Pérez',
      'piastri' => 'Oscar Piastri',
      'ricciardo' => 'Daniel Ricciardo',
      'russell' => 'George Russell',
      'sainz' => 'Carlos Sainz',
      'sargeant' => 'Logan Sargeant',
      'stroll' => 'Lance Stroll',
      'tsunoda' => 'Yuki Tsunoda',
      'max_verstappen' => 'Max Verstappen',
      'zhou' => 'Guanyu Zhou',
      'lawson' => 'Liam Lawson'
    }

    track_names = {
      'bahrain' => 'Bahrain Grand Prix',
      'jeddah' => 'Saudi Arabian Grand Prix',
      'albert_park' => 'Australian Grand Prix',
      'baku' => 'Azerbaijan Grand Prix',
      'miami' => 'Miami Grand Prix',
      'monaco' => 'Monaco Grand Prix',
      'catalunya' => 'Spanish Grand Prix',
      'villeneuve' => 'Canadian Grand Prix',
      'red_bull_ring' => 'Austrian Grand Prix',
      'silverstone' => 'British Grand Prix',
      'hungaroring' => 'Hungarian Grand Prix',
      'spa' => 'Belgian Grand Prix',
      'zandvoort' => 'Dutch Grand Prix',
      'monza' => 'Italian Grand Prix',
      'marina_bay' => 'Singapore Grand Prix',
      'suzuka' => 'Japanese Grand Prix',
      'losail' => 'Qatar Grand Prix',
      'americas' => 'United States Grand Prix',
      'rodriguez' => 'Mexico City Grand Prix',
      'interlagos' => 'São Paulo Grand Prix',
      'vegas' => 'Las Vegas Grand Prix',
      'yas_marina' => 'Abu Dhabi Grand Prix'
    }

    UserPick.all.each do |pick|
      pick.update(driver_id: driver_names[pick.driver_id_tenth.to_s])
      pick.update(race_name: track_names[pick.circuit_id.to_s])
      pick.update(dnf_name: driver_names[pick.driver_id_dnf.to_s])
    end
  end

  def purify_single_pick
    driver_names = {
      'albon' => 'Alex Albon',
      'alonso' => 'Fernando Alonso',
      'bottas' => 'Valtteri Bottas',
      'de_vries' => 'Nyck de Vries',
      'gasly' => 'Pierre Gasly',
      'hamilton' => 'Lewis Hamilton',
      'hulkenberg' => 'Nico Hülkenberg',
      'leclerc' => 'Charles Leclerc',
      'kevin_magnussen' => 'Kevin Magnussen',
      'norris' => 'Lando Norris',
      'ocon' => 'Esteban Ocon',
      'perez' => 'Sergio Pérez',
      'piastri' => 'Oscar Piastri',
      'ricciardo' => 'Daniel Ricciardo',
      'russell' => 'George Russell',
      'sainz' => 'Carlos Sainz',
      'sargeant' => 'Logan Sargeant',
      'stroll' => 'Lance Stroll',
      'tsunoda' => 'Yuki Tsunoda',
      'max_verstappen' => 'Max Verstappen',
      'zhou' => 'Guanyu Zhou',
      'lawson' => 'Liam Lawson'
    }

    track_names = {
      'bahrain' => 'Bahrain Grand Prix',
      'jeddah' => 'Saudi Arabian Grand Prix',
      'albert_park' => 'Australian Grand Prix',
      'baku' => 'Azerbaijan Grand Prix',
      'miami' => 'Miami Grand Prix',
      'monaco' => 'Monaco Grand Prix',
      'catalunya' => 'Spanish Grand Prix',
      'villeneuve' => 'Canadian Grand Prix',
      'red_bull_ring' => 'Austrian Grand Prix',
      'silverstone' => 'British Grand Prix',
      'hungaroring' => 'Hungarian Grand Prix',
      'spa' => 'Belgian Grand Prix',
      'zandvoort' => 'Dutch Grand Prix',
      'monza' => 'Italian Grand Prix',
      'marina_bay' => 'Singapore Grand Prix',
      'suzuka' => 'Japanese Grand Prix',
      'losail' => 'Qatar Grand Prix',
      'americas' => 'United States Grand Prix',
      'rodriguez' => 'Mexico City Grand Prix',
      'interlagos' => 'São Paulo Grand Prix',
      'vegas' => 'Las Vegas Grand Prix',
      'yas_marina' => 'Abu Dhabi Grand Prix'
    }

    update(driver_id: driver_names[driver_id_tenth.to_s])
    update(race_name: track_names[circuit_id.to_s])
    update(dnf_name: driver_names[driver_id_dnf.to_s])
  end
end

app/models/users/user_pick.rb
# frozen_string_literal: true

module Users
  class UserPick < ApplicationRecord
  end
end

app/controllers/user_picks_controller.rb
# frozen_string_literal: true

class UserPicksController < ApplicationController # rubocop:disable Style/Documentation
  before_action :set_user_pick, only: %i[show edit update destroy]

  # GET /user_picks or /user_picks.json
  def index
    @sort_column = params[:sort] || 'user_id'
    @sort_direction = params[:direction] || 'asc'
    @season = Season.find(params[:season_id])
    @position = 1
    allowed_columns = %w[user_id driver_id circuit_id points_earned created_at tenth_finish_position
                         driver_id_dnf driver_id_tenth dnf_finish_position race_name dnf_name]
    @sort_column = allowed_columns.include?(@sort_column) ? @sort_column : 'user_id'
    @user_picks = UserPick.where(season_id: @season.id).includes(:user).order("#{@sort_column} #{@sort_direction}")
    @last_6 = UserPick.last(15) # rubocop:disable Naming/VariableNumber
  end

  # GET /user_picks/1 or /user_picks/1.json
  def show
    @season = Season.find_by_id(@user_pick.season_id)
  end

  # GET /user_picks/new
  def new
    @season = Season.find(params[:season_id])
    @user_pick = UserPick.new
  end

  # GET /user_picks/1/edit
  def edit; end

  # POST /user_picks or /user_picks.json
  def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @user_pick = UserPick.new(user_pick_params)
    respond_to do |format|
      if @user_pick.save
        format.html { redirect_to user_pick_url(@user_pick), notice: 'User pick was successfully created.' }
        format.json { render :show, status: :created, location: @user_pick }
      else
        flash[:error] = @user_pick.errors.full_messages.to_sentence
        format.html { redirect_to "/users/#{user_pick_params[:user_id]}", status: :unprocessable_entity }
        format.json { render json: @user_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_picks/1 or /user_picks/1.json
  def update
    respond_to do |format|
      if @user_pick.update(user_pick_params)
        format.html { redirect_to user_pick_url(@user_pick), notice: 'User pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_pick }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_picks/1 or /user_picks/1.json
  def destroy
    @user_pick.destroy

    respond_to do |format|
      format.html { redirect_to user_picks_url, notice: 'User pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_pick
    @user_pick = UserPick.find(params[:id])
  end

  def user_pick_params
    params.require(:user_pick).permit(:user_id, :driver_id_tenth, :driver_id_dnf, :circuit_id, :season_id)
  end
end

app/controllers/users/user_picks_controller.rb
# frozen_string_literal: true

module Users
  class UserPicksController < ApplicationController # rubocop:disable Style/Documentation
    def index
      @user = User.find_by(username: params[:username])
      @season = Season.find(params[:season_id])
      @races = F1Facade.new.get_schedule(@season.season_year)
      @user_picks = @user.user_picks.where(season_id: @season.id).order(created_at: :asc)
      @position = 1
    end
  end
end

app/helpers/user_picks_helper.rb
# frozen_string_literal: true

module UserPicksHelper
  def toggle_direction(column)
    params[:sort] == column && params[:direction] == 'asc' ? 'desc' : 'asc'
  end
end

app/views/user_picks/_all_pick_styles.html.erb
<%= stylesheet_link_tag 'user_picks', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/user_picks/_buttons_and_links.html.erb
<%= link_to 'Edit', edit_user_pick_path(@user_pick) %> |
<%= link_to 'Back', user_picks_path %> |
<%= button_to 'Delete', user_pick_path(@user_pick), method: :delete %>

app/views/user_picks/_form.html.erb
<%= stylesheet_link_tag 'new_form', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= form_with(model: user_pick, local: true) do |form| %>
  <% if user_pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_pick.errors.count, "error") %> prohibited this user_pick from being saved:</h2>

      <ul>
      <% user_pick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new-pick-wrapper>
    <div class="field">
      <%= form.label :users_id %>
      <%= form.text_field :users_id, class: "select-field" %>
    </div>

    <div class="field">
      <%= form.label :driver_id %>
      <%= form.text_field :driver_id, class: "select-field" %>
    </div>

    <div class="field">
      <%= form.label :circuit_id %>
      <%= form.text_field :circuit_id, class: "select-field" %>
    </div>

    <div class="field">
      <%= form.label :points_earned %>
      <%= form.number_field :points_earned, class: "select-field" %>
    </div>

    <div class="actions">
      <%= form.submit class: "button"%>
    </div>
  </div>
<% end %>

app/views/user_picks/_main_content.html.erb
<main>
  <div class="page-wrapper">
    <%= render partial: 'page_title' %>

    <% @last_6.each do |pick| %>
      <% if pick.points_earned == 0  %>
        <%= pick.assign_finish_position %>
        <%= pick.calculate_points %>
        <%= pick.dnf_points %>
      <% end %>
    <% end %>

    <%= render partial: 'styles' %>
    <div class="scroll-wrapper">
      <%= render partial: 'sort_text' %>
        <div class="user-picks-wrapper">
          <table class="user-picks">
            <%= render partial: 'table_headers' %>
            <%= render partial: 'table_body' %>
          </table>
        </div>
      <!-- <%= render partial: 'new_pick_button> -->
    </div>
    <br>
  </div>
</main>

app/views/user_picks/_new_pick_button.html.erb
<div class="button">
  <%# link_to 'New User Pick', new_user_pick_path, params: {season_id: @season.id} %>
</div>

app/views/user_picks/_race_pick_box.html.erb
<div class="box">
  <p>
    <strong>User:</strong>
    <%= @user_pick.user.name %>
  </p>

  <p>
    <strong>Race Name:</strong>
    <%= @user_pick.race_name %>
  </p>

  <p>
    <strong>10th Driver:</strong>
    <%= @user_pick.driver_id %>
  </p>

  <p>
    <strong>DNF Driver:</strong>
    <%= @user_pick.dnf_name %>
  </p>
</div>

app/views/user_picks/_sort_text.html.erb
<div class="sort-text" >
  <p> Sort the table by clicking the column headers </p>
</div>

app/views/user_picks/_styles.html.erb
<style>
  .center-header {
    text-align: center;
    padding: 10px;
  }
  .center-text {
    text-align: center;
  }
</style>

app/views/user_picks/_stylesheet_show.html.erb
<%= stylesheet_link_tag 'user_picks_show', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/user_picks/_table_body.html.erb
<tbody>
  <% UserPick.all.purify_pick_names %>
  <% @user_picks.each do |user_pick| %>
    <tr>
      <th class="py-2 center-text"><%= user_pick.user.name %></td>
      <td class="py-2 center-text"><%= user_pick.driver_id %></td>
      <td class="py-2 center-text"><%= user_pick.dnf_name %></td>
      <td class="py-2 center-text"><%= user_pick.race_name %></td>
      <td class="py-2 center-text"><%= user_pick.points_earned %></td>
      <!-- <td class="pr-2 hover:underline"><%= link_to 'Show', user_pick %></td> -->
      <td class="hover:underline cursor-pointer">
        <% if JwtService.new.check_for_claim(session[:token], "CanSeeAllTrashCans") %>
          <%= button_to user_pick_path(user_pick), method: :delete do %>
            <%= image_tag "trash-can-solid.svg", class: "image-button" %>
          <% end %>
        <% end %>
      </td>
      <% @position += 1 %>
    </tr>
  <% end %>
</tbody>

app/views/user_picks/edit.html.erb
<h1>Editing User Pick</h1>

<%= render 'form', user_pick: @user_pick %>

<%= link_to 'Show', @user_pick %> |
<%= link_to 'Back', user_picks_path %>

app/views/user_picks/index.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>
  <%= render partial: 'all_pick_styles' %>
  <p id="notice"><%= notice %></p>
  <%= render partial: 'main_content' %>
<% end %>

app/views/user_picks/new.html.erb
<%= stylesheet_link_tag 'new_pick', media: 'all', 'data-turbolinks-track': 'reload' %>
<main>
  <div class="page-wrapper">
    <div class-"form-wrapper">
      <h1 class="title">New User Pick</h1>
        <div class="box">
          <%= render 'form', user_pick: @user_pick %>

          <%= link_to 'Back', user_picks_path, class: "back-button" %>
      </div>
    </div>
  </div>
<main>

app/views/user_picks/show.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>
  <%= render partial: 'stylesheet_show' %>
  <main>
    <p id="notice"><%= notice %></p>

    <% @user_pick.purify_single_pick %>
      <div class="page-wrapper">
        <div class-"form-wrapper">
          <h1 class="title">Your Race Pick</h1>
          <%= render partial: 'race_pick_box' %>
          <!-- <%= render partial: 'buttons_and_links' %> -->
          </div>
      </div>
  </main>
<% end %>