config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/', redirect: '/dashboard'
  # get '/dashboard', to: 'dashboard#index'
  get '/dashboard', to: 'dashboard#index'
  get '/', to: redirect('dashboard')
  resources :sessions, only: %i[new create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  resources :password_resets, only: %i[new create edit update]
  post 'guest_sessions', to: 'sessions#guest_login'

  resources :user_picks
  resources :user_seasons
  resources :users, param: :username do
    resources :user_picks, only: [:index], controller: 'users/user_picks'
  end
  resources :seasons
  resources :leaderboard, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_seasons
  has_many :seasons, through: :user_seasons
  has_many :user_picks

  has_many :user_claims_users
  has_many :user_claims, through: :user_claims_users

  validates :name, presence: true

  # def calculate_total_points
  #   sum = 0

  #   user_picks.each do |user_pick|
  #     sum += user_pick.points_earned
  #   end
  #   update(total_points: sum)
  # end

  def validate_user_password(password_string)
    calculated_hash = calculate_hash(password_string)
    true if pw_hash == calculated_hash
  end

  def update_user_password(password)
    validation_results = validate_user_password_requirements(password)
    # If the pw failed validation, return failure with reasons. Otherwise, return true
    return false if validation_results.length > 1

    save_new_password(password)
    true
  end

  def validate_user_password_requirements(password_string)
    errMessages = []

    # Make sure pw meets min length requirements
    errMessages.push('Password must be at least 6 characters in length') if password_string.length < 6

    # Make sure pw meets max length requirements
    errMessages.push('Password must be less than 30 characters in length') if password_string.length > 30

    # Make sure pw contains at least 1 special character
    if password_string !~ /.*[$&+,:;=?@#|'<>.-^*()%!]+.*/
      errMessages.push('Password must contain at least 1 special character')
    end

    # Make sure pw contains at least 1 number
    errMessages.push('Password must contain at least 1 number') if password_string !~ /.*[0-9]+.*/

    # Make sure pw contains at least 1 capital letter
    errMessages.push('Password must contain at least 1 capital letter') if password_string !~ /.*[A-Z]+.*/

    # Make sure pw contains at least 1 lower case letter
    errMessages.push('Password must contain at least 1 lower case letter') if password_string !~ /.*[a-z]+.*/

    errMessages
  end

  # should the arguments be the password_string and pw_salt?
  def sign_in_user
    # start calling methods below
  end

  private

  def calculate_hash(password_string)
    hashvalue_raw = get_pw_salt_concat(pw_salt, password_string)
    Digest::MD5.hexdigest(hashvalue_raw)
  end

  # Create a hash and salt for a new user password
  # == Params:
  # password_string::
  def save_new_password(password_string)
    salt = SecureRandom.uuid
    prehash = get_pw_salt_concat(salt, password_string)
    calculated_hash = calculate_hash(prehash)
    update(pw_hash: calculated_hash, pw_salt: salt)
  end

  def get_pw_salt_concat(salt, password)
    "#{salt}&$##{password}"
  end
end

app/models/users/user_pick.rb
# frozen_string_literal: true

module Users
  class UserPick < ApplicationRecord
  end
end

app/controllers/users/user_picks_controller.rb
# frozen_string_literal: true

module Users
  class UserPicksController < ApplicationController # rubocop:disable Style/Documentation
    def index
      @user = User.find_by(username: params[:username])
      @season = Season.find(params[:season_id])
      @races = F1Facade.new.get_schedule(@season.season_year)
      @user_picks = @user.user_picks.where(season_id: @season.id).order(created_at: :asc)
      @position = 1
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

require 'securerandom'

class UsersController < ApplicationController
  skip_before_action :authorize, only: :create
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @season = Season.find(params[:season_id])
    @user = User.find_by(username: params[:username])
    @user_season = UserSeason.where(user_id: @user.id, season_id: @season)
    @next_race = @season.next_race_weekend(@season.season_year)

    if @next_race != 'This season is over. Please select a different season.'
      @qualifying = F1Service.new.get_qualifying(@season.season_year, @next_race[:round])
    else
      'This Season Is Over. Please Select A Different Season.'
    end
    # @qualifying = F1Service.new.get_qualifying(@user.seasons.last.season_year, 11)
    @drivers = F1Facade.new.get_drivers(@user.seasons.where(id: @season.id).first.season_year)
    @position = 1
  end

  # GET /users/new
  def new
    @season = Season.last
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @season = Season.last
    respond_to do |format|
      if @user.save
        UserSeason.create!(user_id: @user.id, season_id: @season.id)
        format.html { redirect_to '/', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def save_new_user_password(password)
    success = @user.update_user_password(password)
    if success
      format.json { render :show, status: :ok, location: @user }
    else
      format.json { render json: @user.errors, status: :bad_request }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    User.find_by(username: session[:username])
  end
  # def set_user
  #   require 'pry'; binding.pry
  #   @user = User.find_by(username: params[:username])
  #   session[:username] = @user.username
  # end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :username)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= stylesheet_link_tag 'new_form', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "select-field" %>
  </div>

  <% if session[:username] == @user.username || JwtService.new.check_for_claim(session[:token], "CanSeeAllSubmitButtons") %>
    <div class="actions">
      <%= form.submit class: "button" %>
    </div>
  <% end %>
<% end %>

app/views/users/_header.html.erb
<div>
  <h2 class="main-header">This Week's Race Picks: </h1>
</div>

app/views/users/_main_content_show.html.erb
<main>
  <div class="page-wrapper">
    <div class="user-wrapper"> <!-- This starts the user show page row -->
      <%= render partial: 'user_score' %>
      <div class="user-picks-wrapper"> <!-- This starts the user picks column -->
        <%= render partial: 'header' %>
        <div> <!-- race name -->
          <% if @next_race == 'This season is over. Please select a different season.' %>
            <%= @next_race %>
          <% else %>
            <h2 class="race-header"><%= @next_race[:raceName] %></h2>
        </div>
        <div class="submit-picks"> <!-- submit picks form -->
          <%= render partial: 'selection_wrapper' %>
          <%= render partial: 'quali_results' %>
        <% end %>
        </div>
      </div><!-- This ends the user picks column -->
    </div> <!-- This ends the user show page row -->
  </div> <!-- This ends page wrapper -->
</main>

app/views/users/_quali_results.html.erb
<div class="quali-results"> <!-- quali results -->
  <h4 class="submit-headers">Qualifying Results</h2>
  <% if @qualifying[:MRData][:RaceTable][:Races].empty? %>
    <p>Qualifying results not available yet</p>
  <% else %>
    <table>
    <thead>
      <tr>
        <th class="py-2 center-header">Position</th>
        <th class="py-2 center-header">Driver Name</th>
        <th class="py-2 center-header">Constructor</th>
      </tr>
    </thead>
    <tbody>
      <% @qualifying[:MRData][:RaceTable][:Races][0][:QualifyingResults].each do |driver| %>
        <tr>
          <th class="py-2 center-text"><%= driver[:position] %></td>
          <td class="py-2 center-text"><%= "#{driver[:Driver][:givenName]} #{driver[:Driver][:familyName]}" %></td>
          <td class="py-2 center-text"><%= driver[:Constructor][:name] %></td>
          <% @position += 1 %>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% end %>
</div> <!-- This ends the quali results -->

app/views/users/_selection_wrapper.html.erb
<div class="selection-wrapper">
  <h4 class="submit-headers">Your Picks</h4>
  <div class="selections">
    <%= form_with(model: UserPick.new, url: '/user_picks', method: :post) do |form| %>
      <%= form.hidden_field :circuit_id, value: @next_race[:Circuit][:circuitId] %>
      <br> 
      <%= form.hidden_field :user_id, value: @user.id %>
      <%= form.hidden_field :season_id, value: @season.id %>
      <br>
      <label for="pick_tenth_place_id">10th Place Finisher:</label>
      <%= form.collection_select :driver_id_tenth, @drivers, :driver_id, :name %>
      <br>
      <label for="pick_first_dnf_id">First DNF:</label>
      <%= form.collection_select :driver_id_dnf, @drivers, :driver_id, :name %>
      <br>
      <%= form.submit "Submit Picks", class: "button" %>
    <% end %>
    <p class="error-text"> If you are being redirected, it means you chose the same driver in both fields or you already have a pick for this weekend </p>
  </div>
</div>

app/views/users/_styles.html.erb
<style>
  .center-header {
    text-align: center;
    padding: 10px;
  }
  .center-text {
    text-align: center;
  }
  .rounded-box {
   border: 2px solid #FF1801;
    border-radius: 10px;
    padding: 10px;
  }
</style>

app/views/users/_stylesheet.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/users/_user_score.html.erb
<div class="user-score"> <!-- This starts the user scoring column -->
  <h3 class="points-header">Points Accrued</h3> 
  <div class="box">
    <p>
      <span class="catagory-text">Name:</span>
      <%= @user.name %>
    </p>

    <p>
      <span class="catagory-text">Total points:</span>
      <% @user_season.first.calculate_total_points %>
      <%= @user_season.first.total_points %>
    </p>

    <p>
      <span class="catagory-text">Points from Last Race:</span>
      <% if @user_season.first.total_points == 0 %>
        <%= 0 %>
      <% else %>
        <%= @user_season.first.user_picks.sort.last.points_earned %>
      <% end %>
    </p>
  </div> <!-- This ends the box div -->
  <%= button_to "View Previous Picks", user_user_picks_path(@user), params: {season_id: @season.id, username: @user.username}, method: :get, class: "button" %>
</div> <!-- This ends the user scoring column -->

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user_index', media: 'all', 'data-turbolinks-track': 'reload' %>
<p id="notice"><%= notice %></p>
<main>
  <div class="page-wrapper">
    <div class-"form-wrapper">
      <div class="users-page">
        <h1 class="title">Users</h1>
        <div class="season-table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Total points</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <th><%= user.name %></td>
                  <td><%= user.total_points %></td>
                  <td><%= link_to 'Show', user %></td>
                  <td><%= link_to 'Edit', edit_user_path(user) %></td>
                  <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'New User', new_user_path, class: "button"%>
      </div>
    </div>
  </div>
<main>

app/views/users/new.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>  
  <%= stylesheet_link_tag 'new_user', media: 'all', 'data-turbolinks-track': 'reload' %>
  <main>
    <div class="page-wrapper">
      <div class-"form-wrapper">
        <h1 class="title">New User</h1>
          <div class="box">
          <%= render 'form', user: @user, params: {season_id: @season.id} %>
        </div>
        <%= link_to 'Back', users_path, class: "back-button" %>
      </div>
    </div>
  <main>
<% cache("cached_view_key", expires_in: 15.minutes) do %>

app/views/users/show.html.erb
<% cache("cached_view_key", expires_in: 15.minutes) do %>
  <%= render partial: 'stylesheet' %>
  <p id="notice"><%= notice %></p>
  <%= render partial: 'styles' %>
  <%= render partial: 'main_content_show' %>
<% end %>