config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/', redirect: '/dashboard'
  # get '/dashboard', to: 'dashboard#index'
  get '/dashboard', to: 'dashboard#index'
  get '/', to: redirect('dashboard')
  resources :sessions, only: %i[new create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  resources :password_resets, only: %i[new create edit update]
  post 'guest_sessions', to: 'sessions#guest_login'

  resources :user_picks
  resources :user_seasons
  resources :users, param: :username do
    resources :user_picks, only: [:index], controller: 'users/user_picks'
  end
  resources :seasons
  resources :leaderboard, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag 'header', media: 'all', 'data-turbolinks-track': 'reload' %>
<style>
    @media(max-width:1520px) {
        .left-svg {
            display: none;
        }
    }
  
    /* small css for the mobile nav close */
    #nav-mobile-btn.close span:first-child {
        transform: rotate(45deg);
        top: 4px;
        position: relative;
        background: #a0aec0;
    }
  
    #nav-mobile-btn.close span:nth-child(2) {
        transform: rotate(-45deg);
        margin-top: 0px;
        background: #a0aec0;
    }
  </style>
  
  <header id="page_header" class="fixed top-0 z-10 w-full h-20 bg-white shadow-lg">
    <div class="flex items-center h-full mx-20 justify-between">
      <a href="/" class="relative flex items-center h-full font-black leading-none cursor-pointer hover:opacity-75">
        <%= image_tag 'logo2.png', title: "P10 Racing Logo", class: "logo h-5 shadow-sm" %>
      </a>  
      
      
      <% unless @hide_header == true %>
        <div class='flex items-center'> 
          <% if JwtService.new.check_for_claim(session[:token], "CanViewTestDiv") %>
            <span>Im the test div</span>
          <% end %>
          <% if JwtService.new.check_for_claim(session[:token], "CanViewTest2Div") %>
            <span> "I should be invisible"></span>
          <% end %>
          <span class="welcome-message"><%= "Welcome #{session[:username]}" %></span>
          <div class="navbar">
            <ul class="nav-menu">
              <li class="nav-item">
                <%= button_to "Leaderboard", leaderboard_index_path, params: {season_id: @season.id}, method: :get, class: 'header-button' %>              
              </li>
              <li class="nav-item"> 
                <%= button_to "Season Home", season_path(@season.id), method: :get, class: 'middle-header-button' %>
              </li>
              <li class="nav-item">
                <%= button_to "All Picks", user_picks_path, params: {season_id: @season.id}, method: :get, class: 'header-button' %>
              </li>
              <li class="nav-item">
                <%= button_to "Logout",  logout_path, method: :delete, class: 'middle-header-button' %>
              </li>
            </ul>
            <div class="hamburger">
              <span class="bar"></span>
              <span class="bar"></span>
              <span class="bar"></span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P10Racing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>

    <!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.9.2/tailwind.min.css">
  </head>

  <body>
      <%= render partial: "layouts/header" %>
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: type %>
    <% end %>
    <div class="mt-20">
      <%= yield %>
    </div>
  </body>
</html>